lio_base:
    # common params
    lidar_topic: "/ouster/points"
    imu_topic: "/ouster/imu"
    time_sync_en: false

    # lidar params
    lidar_type: 3  # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
    scan_line: 64
    blind: 1
    time_scale: 1e-3

    # imu params
    acc_cov: 0.2
    gyr_cov: 0.2
    b_acc_cov: 0.002
    b_gyr_cov: 0.002

    # lidar-imu params
    extrinsic_T: [0.0, 0.0, 0.0]
    extrinsic_R: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

    # lidar-imu params
    imu2base_T: [ 0.0, 0.0, 0.35 ]
    imu2base_R: [1, 0, 0,
                 0, 1, 0,
                 0, 0, 1]

    # preprocess params
    point_filter_num: 3
    filter_size_surf: 0.5
    feature_extract_enable: false

    # filter params
    filter_size_map: 0.5
    extrinsic_est_en: true  # true: enable the online estimation of IMU-LiDAR extrinsic
    plane_threshold: 0.1    # default=0.1
    max_iteration: 3

    nearest_neighbor_type: 2 # 1 for IKD_TREE, 2 for IVOX

    # frame info params
    body_frame: "ouster_lidar_link"
    init_frame: "odom"
    base_frame: "base_link"

    odom_topic: "odom"
    path_topic: "lio_path"
    cloud_world_topic: "cloud_registered_world"
    cloud_imu_topic: "cloud_registered_imu"
    scan_imu_topic: "scan"

faster_lio:
    # ivox params
    ivox_grid_resolution: 0.5   # default=0.2
    ivox_nearby_type: 18        # 6, 18, 26

scan:
    max_height: 1.0
    min_height: -0.35
    range_max: 200.0
    range_min: 0.0
